language: go

go:
    - "1.11"
    - "1.12"
    - "1.13"
    - "1.14"

env:
    - ROS_DOCKER=ros:kinetic-ros-base
    - ROS_DOCKER=ros:melodic-ros-base
    - ROS_DOCKER=ros:noetic-ros-base

sudo: required

services:
    - docker

install:
    - docker build -f .travis/Dockerfile -t akio/rosgo . --build-arg ROS_DOCKER_TAG=$ROS_DOCKER

script:
    - docker run -v $GOROOT:/usr/local/go akio/rosgo

